---
    name: CI
    
    on:
      push:
        branches:
          - main
        tags-ignore:
          - "*"
      pull_request:
        branches:
          - main
      workflow_dispatch: {}
    
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    
    jobs:
      java-build:
        uses: jqassistant-tooling/jqassistant-github-actions/.github/workflows/ci.yml@main
        with:
          publish_snapshots: true
        secrets:
          ossrh_username: ${{ secrets.OSSRH_USERNAME }}
          ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
          ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
          ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      typescript-test:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os: [ ubuntu-latest, windows-latest, macos-latest ]
        steps:
          - uses: actions/checkout@v3
          - name: Setup Node.js (LTS)
            uses: actions/setup-node@v3
            with:
              node-version: 'lts/*'
          - name: Install dependencies
            run: npm install
            working-directory: ./typescript
          - name: Run tests
            run: npm run test
            working-directory: ./typescript
